environment:
  matrix:
    - platform: x64

image: Visual Studio 2015

clone_script:
  - cmd: git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%
  - git submodule update --init --recursive

init:
  - yarn config set msvs_version 2015 # we need this to build `pty.js`

install:
  - ps: Install-Product node 9.8 x64
  - set CI=true
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - mv package.json package.json.bak
  - cd hyper
  - yarn
  - cd ..
  - mv package.json.bak package.json

build: off

matrix:
  fast_finish: true

shallow_clone: true

on_success:
  - yarn run dist
  - ps: Get-ChildItem .\dist\* | % { Push-AppveyorArtifact $_.FullName }
