# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    macos:
      xcode: "9.0"

    working_directory: ~/repo

    steps:
      - checkout
      - run: git submodule update --init --recursive

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-{{ .Branch }}-
          - v1-dependencies-

      - run: yarn global add greenkeeper-lockfile@1
      - run: yarn install
      - run: greenkeeper-lockfile-update

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn run dist

      - run: greenkeeper-lockfile-upload

      - store_artifacts:
          path: dist/
      
      - persist_to_workspace:
          root: .
          paths:
            - dist

  upload:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Installing Uploader
          command: go get github.com/aktau/github-release
      - run:
          name: Uploading Binaries
          command:
            >-
              github-release release -u chabou -r hyper-plugins-screenshots -t `git describe --tags`;
              for file in ./dist/*;
              do
               github-release upload -u chabou -r hyper-plugins-screenshots -R -t `git describe --tags` -n ${file##*/} -f $file;
              done
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - upload:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
